[package]
name = "tidal-player-audio"
description = "Decode and audio output engine for tidal-player"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["alsa"]
alsa = ["dep:alsa"]

[dependencies]
alsa = { workspace = true, optional = true }
symphonia = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
